name: Build and publish to TestPyPI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 20
    - run: "git fetch --depth=1 origin +refs/tags/*:refs/tags/* || :"
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pep517 and twine
      run: python -m pip install pep517 twine --user
    - name: Build a binary wheel and a source tarball
      run: python -m pep517.build --source --binary --out-dir dist/ ./
    - name: twine check
      run: python -m twine check dist/*
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_PASSWORD }}
        repository_url: https://test.pypi.org/legacy/
